version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PGPORT=5000
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      -  5000:5000
  
  redis:
    image: redis:alpine
    ports:
      - 6379:6379