version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PORT=5000
      - REDIS_PORT=6379
      - REDIS_HOST="127.0.0.1"
    ports:
      -  5000:5000
    depends_on:
      - redis
  
  redis:
    image: redis:alpine