apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: azalurg/node-api-todo:1.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_HOST
              value: "127.0.0.1"
            - name: MONGO_PORT
              value: "27017"
            - name: MONGO_DATABASE
              value: "Kubernetes"
            - name: API_PORT
              value: "5000"
            - name: MONGO_HOST
              value: "127.0.0.1"
            - name: REDIS_PORT
              value: "6379"

---

apiVersion: v1
kind: Service
metadata:
  name: server-service-clusterip
spec:
  selector:
    app: server
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata:
  name: server-service-nodeport

spec:
  selector:
    app: server

  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500

  type: NodePort