version: '3'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: ./backend
    environment:
      - PGPORT=5000
      - REDIS_PORT=6379
      - REDIS_HOST=127.0.0.1
    ports:
      - 5000:5000
  
  myredis:
    image: 'redis:alpine'
    ports: 
      - 6379:6379