apiVersion: v1
kind: PersistantVolume
metadata:
  name: pv-local
  labels:
    type: local

space:
  storageClassName: manual
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hosetPath:
    path: "/home/komar/k8spv"